
export const config = {
  /**
   * The url (including http(s)://) to a test server.
   */
  testRoot: 'https://scoring2',

  /**
   * The root to send API calls to
   */
  apiRoot: 'game-session/',

  /**
   * The root of the client application (as generated by build)
   */
  clientRoot: 'client/',

  /**
   * The prefix for the browser's window title.
   */
  titlePrefix: 'Trackscore.nl',
};
