name: CI/CD Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'scoring_client/**'
  pull_request:
    branches:
      - master
    paths:
      - 'scoring_client/**'

jobs:
  # wait for build and test, then copy files from scoring_client to the server via FTP
  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-test-client
    steps:
      - name: FTP Deploy Client Build
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public_html/client/
          server-dir: /public_html/client/
          timeout: 180000

  # build and test the client
  build-and-test-client:
    name: Build & Test Client
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: scoring_client/package-lock.json

      - name: Build Client
        run: |
          cd scoring_client
          npm ci
          npm run build
